/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function outOfBandSenderCreate(config: string): Promise<number>
export function outOfBandReceiverCreate(msg: string): number
export function outOfBandSenderAppendMessage(handle: number, msg: string): void
export function outOfBandSenderAppendService(handle: number, service: string): void
export function outOfBandSenderAppendServiceDid(handle: number, did: string): void
export function outOfBandReceiverExtractMessage(handle: number): string
export function outOfBandSenderToMessage(handle: number): string
export function outOfBandReceiverConnectionExists(handle: number, connHandles: Array<number>): Promise<number>
export function outOfBandReceiverBuildConnection(handle: number): Promise<string>
export function outOfBandSenderGetThreadId(handle: number): string
export function outOfBandReceiverGetThreadId(handle: number): string
export function outOfBandSenderSerialize(handle: number): string
export function outOfBandReceiverSerialize(handle: number): string
export function outOfBandSenderDeserialize(oobData: string): number
export function outOfBandReceiverDeserialize(oobData: string): number
export function outOfBandSenderRelease(handle: number): void
export function outOfBandReceiverRelease(handle: number): void
