/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function outOfBandSenderCreate(config: string): Promise<number>
export function outOfBandReceiverCreate(msg: string): number
export function outOfBandSenderAppendMessage(handle: number, msg: string): void
export function outOfBandSenderAppendService(handle: number, service: string): void
export function outOfBandSenderAppendServiceDid(handle: number, did: string): void
export function outOfBandReceiverExtractMessage(handle: number): string
export function outOfBandSenderToMessage(handle: number): string
export function outOfBandReceiverConnectionExists(handle: number, connHandles: Array<number>): Promise<number>
export function outOfBandReceiverBuildConnection(handle: number): Promise<string>
export function outOfBandSenderGetThreadId(handle: number): string
export function outOfBandReceiverGetThreadId(handle: number): string
export function outOfBandSenderSerialize(handle: number): string
export function outOfBandReceiverSerialize(handle: number): string
export function outOfBandSenderDeserialize(oobData: string): number
export function outOfBandReceiverDeserialize(oobData: string): number
export function outOfBandSenderRelease(handle: number): void
export function outOfBandReceiverRelease(handle: number): void
export function mediatedConnectionGeneratePublicInvite(publicDid: string, label: string): string
export function mediatedConnectionGetPwDid(handle: number): string
export function mediatedConnectionGetTheirPwDid(handle: number): string
export function mediatedConnectionGetThreadId(handle: number): string
export function mediatedConnectionGetState(handle: number): number
export function mediatedConnectionGetSourceId(handle: number): string
export function mediatedConnectionCreate(sourceId: string): Promise<number>
export function mediatedConnectionCreateWithInvite(sourceId: string, details: string): Promise<number>
export function mediatedConnectionCreateWithConnectionRequest(request: string, agentHandle: number): Promise<number>
export function mediatedConnectionCreateWithConnectionRequestV2(request: string, pwInfo: string): Promise<number>
export function mediatedConnectionSendHandshakeReuse(handle: number, oobMsg: string): Promise<void>
export function mediatedConnectionUpdateStateWithMessage(handle: number, message: string): Promise<number>
export function mediatedConnectionHandleMessage(handle: number, message: string): Promise<number>
export function mediatedConnectionUpdateState(handle: number): Promise<number>
export function mediatedConnectionDeleteConnection(handle: number): Promise<number>
export function mediatedConnectionConnect(handle: number): Promise<string | null>
export function mediatedConnectionSerialize(handle: number): string
export function mediatedConnectionDeserialize(connectionData: string): number
export function mediatedConnectionRelease(handle: number): void
export function mediatedConnectionInviteDetails(handle: number): string
export function mediatedConnectionSendPing(handle: number, comment?: string | undefined | null): Promise<void>
export function mediatedConnectionSendDiscoveryFeatures(handle: number, query?: string | undefined | null, comment?: string | undefined | null): Promise<void>
export function mediatedConnectionInfo(handle: number): Promise<string>
export function mediatedConnectionMessagesDownload(connHandles: Array<number>, statusCodes?: string | undefined | null, uids?: string | undefined | null): Promise<string>
export function mediatedConnectionSignData(handle: number, data: Buffer): Promise<Buffer>
export function mediatedConnectionVerifySignature(handle: number, data: Buffer, signature: Buffer): Promise<boolean>
