name: dev

on:
  push:
    branches:
      - "**"

jobs:
  workflow-setup:
    runs-on: ubuntu-20.04
    outputs:
      PUBLISH_VERSION: ${{ steps.run-info.outputs.publish-version }}
    steps:
      - name: "Git checkout"
        uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.64.0
      - name: "Construct CI run-info"
        id: run-info
        uses: ./.github/actions/construct-run-info
  build-napi-artifacts:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: |-
              set -e
              sudo apt-get update -y
              sudo apt-get install -y libsodium-dev libssl-dev libzmq3-dev
              npm run build:napi -- --target x86_64-unknown-linux-gnu
              strip *.node
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
            build: |-
              set -e
              cd wrappers/vcx-napi-rs
              apk update
              apk upgrade
              apk add openssl-dev zeromq-dev
              npm run build:napi
              strip *.node
          - host: macos-latest
            target: x86_64-apple-darwin
            build: |
              brew install libsodium openssl zmq
              npm run build:napi
              strip -x *.node
          - host: macos-latest
            target: aarch64-apple-darwin
            build: |
              brew install libsodium openssl zmq
              sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*;
              export CC=$(xcrun -f clang);
              export CXX=$(xcrun -f clang++);
              SYSROOT=$(xcrun --sdk macosx --show-sdk-path);
              export CFLAGS="-isysroot $SYSROOT -isystem $SYSROOT";
              npm run build:napi
              strip -x *.node
    name: stable - ${{ matrix.settings.target }} - node@18
    runs-on: ${{ matrix.settings.host }}
    defaults:
      run:
        shell: bash
        working-directory: ./wrappers/vcx-napi-rs
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        if: ${{ !matrix.settings.docker }}
        with:
          node-version: 18
      - name: Install
        uses: dtolnay/rust-toolchain@stable
        if: ${{ !matrix.settings.docker }}
        with:
          targets: ${{ matrix.settings.target }}
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            target/
          key: ${{ matrix.settings.target }}-cargo-registry
      - name: Check cache
        run: ls ${{ github.workspace }}/target/
      - name: Install dependencies
        run: npm install
      - name: Build in docker
        uses: addnab/docker-run-action@v3
        if: ${{ matrix.settings.docker }}
        with:
          image: ${{ matrix.settings.docker }}
          options: --user 0:0 -v ${{ github.workspace }}/.cargo-cache/git/db:/usr/local/cargo/git/db -v ${{ github.workspace }}/.cargo/registry/cache:/usr/local/cargo/registry/cache -v ${{ github.workspace }}/.cargo/registry/index:/usr/local/cargo/registry/index -v ${{ github.workspace }}:/build -w /build
          run: ${{ matrix.settings.build }}
      - name: Build
        run: ${{ matrix.settings.build }}
        if: ${{ !matrix.settings.docker }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bindings-${{ matrix.settings.target }}
          path: ${{ github.workspace }}/wrappers/vcx-napi-rs/*.node
          if-no-files-found: error
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - workflow-setup
      - build-napi-artifacts
    defaults:
      run:
        shell: bash
        working-directory: ./wrappers/vcx-napi-rs
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/wrappers/vcx-napi-rs/artifacts
      - name: List artifacts
        run: ls -R ./artifacts
      - name: Move artifacts
        run: npm run artifacts
      - name: List packages
        run: ls -R ./npm
        shell: bash
      - name: Publish
        run: |
          if [[ "$PUBLISH_VERSION" ]]
          then
            npm set "//registry.npmjs.org/:_authToken" $NPMJS_TOKEN
            npm version $PUBLISH_VERSION
            npm run prepublish
            npm publish
          else
             echo "New version was not defined, skipping release."
          fi
        env:
          NPMJS_TOKEN: ${{ secrets.NPMJS_TOKEN }}
          PUBLISH_VERSION: ${{needs.workflow-setup.outputs.PUBLISH_VERSION}}
